apiVersion: v1
kind: ConfigMap
metadata:
  name: dustin-scan-config
  namespace: dustin-scan
data:
  # 운영 환경 설정
  NODE_ENV: 'production'

  # 운영용 Chain URL (실제 운영 서버)
  CHAIN_URL: 'http://dustin-chain-service:3000'
