apiVersion: v1
kind: ConfigMap
metadata:
  name: dustin-scan-config
  namespace: dustin-scan
data:
  # 운영 환경 설정
  NODE_ENV: 'production'

  # 운영용 Chain URL (EC2 Docker에서 실행 중)
  CHAIN_URL: 'http://172.31.45.89:3000'
