apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: dustin-scan
  labels:
    app: dustin-scan
    component: indexer
spec:
  replicas: 1 # 고정 1개 (스케일링 하지 않음)
  selector:
    matchLabels:
      app: dustin-scan
      component: indexer
  template:
    metadata:
      labels:
        app: dustin-scan
        component: indexer
    spec:
      containers:
        - name: indexer
          image: deukchunjang/dustin-scan-backend:latest
          imagePullPolicy: Always
          command: ['node', 'dist/apps/indexer/src/main']
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          env:
            # ConfigMap에서 환경변수 가져오기
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: NODE_ENV
            - name: INDEXER_PORT
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: INDEXER_PORT
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dustin-scan-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: DB_USERNAME
            - name: DB_SYNCHRONIZE
              value: 'true' # Indexer만 스키마 동기화
            - name: CHAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: CHAIN_URL
            - name: HEALTHCHECK_PORT
              valueFrom:
                configMapKeyRef:
                  name: dustin-scan-config
                  key: INDEXER_PORT
            # Secret에서 민감한 정보 가져오기
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dustin-scan-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dustin-scan-secret
                  key: DB_DATABASE
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
