apiVersion: v1
kind: Secret
metadata:
  name: dustin-scan-secret
  namespace: dustin-scan
type: Opaque
data:
  # base64로 인코딩된 DB 호스트 (로컬 테스트용)
  # 실제 값: "postgres-service"
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==

  # base64로 인코딩된 비밀번호
  # 실제 값: "1234"
  DB_PASSWORD: MTIzNA==

  # base64로 인코딩된 데이터베이스 이름
  # 실제 값: "dustin_scan"
  DB_DATABASE: ZHVzdGluX3NjYW4=
